### ISSUE TITLE
A few observations about the code

### ISSUE THREAD

**Issue by algernon** [ToyKeeper/Kaleidoscope-LED-Wavepool#2]
- [ ] `library.properties` credits me with being the author of the plugin. As great as the plugin is, the credit is yours =)
- [ ] `WavepoolEffect.rc2pos` could be moved to PROGMEM, to drastically reduce memory use. It is only ever used to look data up from, so it does not need to be in writable memory. The downside of this would be that it would use large amounts of progmem space then. (In my own case, I have about 650 bytes of RAM free, but slightly less progmem space)
- [ ] `WavepoolEffect::ColorComputer` and the `WAVEPOOL` macro could be dropped. I suppose those are remnants of `LED-Stalker`?
- [ ] `WavepoolEffect::init` does not seem to be used anywhere, and as `WavepoolEffect::map` is static, it is initialized to zeros anyway, so the code would appear to be not needed.

**Comment by ToyKeeper** [comment]
Thanks!  Fixed in commits 6e5a10a1c34a61f055f0855dd03cfbc1d99988ab and 11c643bba820f11d69020a7a41af298e1f047adf.

I doubt the rc2pos table will use any more ROM than it did before, since it's initialized to specific values.  Those values would be in the ROM anyway, so the copy in RAM was redundant.

It'd be nice if there was already a table somewhere mapping key numbers to geometric position, but I didn't see one with the desired 14x5 layout.  It seems like something which would be more appropriate elsewhere in the code, in case anything else needs it.

**Comment by algernon** [comment]
There is `KeyboardHardware.getLedIndex(row, col)` which might be useful to you, but it uses a [slightly different](https://github.com/keyboardio/Kaleidoscope-Hardware-Model01/blob/3571a56ae60afb716189acac0dbccecfb7f2e24d/src/Kaleidoscope-Hardware-Model01.cpp#L11-L16) lookup table to map key positions to LED positions.

**Comment by ToyKeeper** [comment]
Ah, interesting.  So that's why the chaser mode looks like it does...
I could perhaps reduce the size a little by using index instead of row and column, but I'd still need a table to translate between index and coordinates, since it's still 16x4 vs 14x5.
